build: off

environment:
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - CONDA_PYTHON_VERSION: "3.8"
    - CONDA_PYTHON_VERSION: "3.9"
    - CONDA_PYTHON_VERSION: "3.10"

init:
  - "ECHO %CONDA_PYTHON_VERSION% %MINICONDA%"
  - call %MINICONDA%\Scripts\activate.bat
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -n questplus -c conda-forge python=%CONDA_PYTHON_VERSION% pytest numpy scipy xarray json_tricks"
  - call conda activate questplus
#  - conda list

install:
  - python setup.py build

  # Build & install sdist.
  - python setup.py sdist --formats=zip
#  - pip install --no-deps dist/questplus-*.zip
#  - pip uninstall --yes questplus

  # Build & install wheel.
  - python setup.py bdist_wheel
#  - pip install --no-deps dist/questplus-*.whl
#  - pip uninstall --yes questplus

  - ps: Remove-Item –path dist, build –recurse
  - pip install --no-deps .

test_script:
  - py.test
