[tool.black]
target-version = ['py36']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
(
  versioneer.py
  | _version.py
  | ^/questplus/tests/
)
'''

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "questplus/_version.py"
versionfile_build = "questplus/_version.py"
tag_prefix = ""
